django-legacy/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vending_machine.urls')),
]

django-legacy/vending_machine/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'vendingmachine'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.top_up, name='add'),
    path('flush', views.flush, name='flush'),
    path('purchase/', views.purchase, name='purchase'),
    path('history/', views.history, name='history'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django-legacy/vending_machine/models.py
from django.db import models


class Beverage(models.Model):
    """
    Represents a beverage in the vending machine.
    """
    name = models.CharField(max_length=256)
    price = models.FloatField(default=0.0)
    stock = models.IntegerField(default=0)

    def increment_stock(self):
        self.stock += 1

    def decrement_stock(self):
        assert self.stock > 0, "Stock is already empty"
        self.stock -= 1

    def enough_price(self, to_check: float) -> bool:
        return to_check >= self.price

    def available(self) -> bool:
        return self.stock > 0

    def getImageURL(self):
        return self.name.replace(" ", "")

    def __str__(self) -> str:
        return f"{self.name}(${self.price}, {self.stock})"


class Transaction(models.Model):
    """
    Represents a vending machine transaction.
    """
    beverage = models.ForeignKey(Beverage, on_delete=models.CASCADE)
    inserted_amount = models.FloatField()
    return_amount = models.FloatField()
    trans_time = models.DateTimeField()

    def calc_return(self) -> float:
        return self.beverage.price - self.inserted_amount

django-legacy/vending_machine/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone

from .models import Beverage, Transaction


def index(request: HttpRequest):
    current_balance: float = request.session.get("balance", 0)

    beverages = Beverage.objects.all()
    context = {
        'balance': current_balance,
        'beverages': beverages
    }

    return render(request, 'vending_machine/index.html', context=context)


def top_up(request: HttpRequest):
    balance: float = request.session.get("balance", 0)
    try:
        amount = float(request.POST['amount'])
        balance = balance + amount
    except KeyError:
        print(request.POST)
        return HttpResponse(f"cannot handle input!")

    request.session['balance'] = balance
    return HttpResponseRedirect(reverse('vendingmachine:index'))


def flush(request: HttpRequest):
    try:
        assert request.method == "POST", "not a post request"
        assert bool(request.POST['flush'])
        del request.session['balance']
    except AssertionError as msg:
        print(msg)
    finally:
        return HttpResponseRedirect(reverse('vendingmachine:index'))


def purchase(request: HttpRequest):
    try:
        assert request.method == "POST", "not a post request"
        item_id = request.POST['id']
        beverage = get_object_or_404(Beverage, pk=item_id)
        inserted_amount = request.session['balance']
        return_amount = inserted_amount - beverage.price
        assert return_amount >= 0, "insufficient amount"
        transaction = Transaction(beverage=beverage, inserted_amount=inserted_amount, return_amount=return_amount,
                                  trans_time=timezone.now())
        # print(f"Success: {beverage}, inserted: {inserted_amount}, time: {timezone.now()}")
        beverage.decrement_stock()
        beverage.save()
        transaction.save()
        request.session['balance'] = return_amount
    except AssertionError as msg:
        print(msg)
    finally:
        return HttpResponseRedirect(reverse('vendingmachine:index'))


def history(request: HttpRequest):
    transactions = Transaction.objects.all()
    context = {
        'transactions': transactions,
    }
    return render(request, 'vending_machine/history.html', context=context)

django-legacy/vending_machine/templates/vending_machine/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vending Machine</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body class="bg-light">
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>

</html>

django-legacy/vending_machine/templates/vending_machine/history.html
{% extends "vending_machine/base.html" %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Vending Machine</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vendingmachine:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">History</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<ol class="list-group list-group-numbered">
    {% for transaction in transactions %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">{{transaction.beverage.name}}</div>
            Inserted Amount: ${{transaction.inserted_amount}} <br>
            Returned Amount: ${{transaction.return_amount}} <br>
            Transaction Time: {{transaction.trans_time}} <br>
        </div>
    </li>
    {% endfor %}
</ol>

{% endblock %}

django-legacy/vending_machine/templates/vending_machine/index.html
{% extends "vending_machine/base.html" %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Vending Machine</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vendingmachine:history' %}">History</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<br>

<div class="Balance">
    <div class="border border-dark rounded mx-5 ">
        <div class="h4 text-center">Current balance: ${{balance}}</div>
        <div class="text-center">
            <span class="h5">Top Up: </span>
        </div>
        <div class="row my-4 mx-auto" style="width: 50%; align-content: center;">
            <div class="col">
                <form action="{% url 'vendingmachine:add' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="amount" value="2.00">
                    <button type="submit" class="btn btn-primary"> $2.00</button>
                </form>
            </div>
            <div class="col">
                <form action="{% url 'vendingmachine:add' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="amount" value="5.00">
                    <button type="submit" class="btn btn-primary"> $5.00</button>
                </form>
            </div>
            <div class="col">
                <form action="{% url 'vendingmachine:add' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="amount" value="10.00">
                    <button type="submit" class="btn btn-primary">$10.00</button>
                </form>
            </div>
            <div class="col">
                <form action="{% url 'vendingmachine:flush' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="flush" value="True">
                    <button type="submit" class="btn btn-danger">Reset</button>
                </form>
            </div>
        </div>
    </div>
</div>

<br>

<div id="inventory">
    <h1 class="text-center">Inventory</h1>
    <div class="row mx-5">
        {% for beverage in beverages %}
        <div class="col">
            <div class="card rounded-3">
                {% load static %}
                {% with 'vending_machine/'|add:beverage.getImageURL|add:'.png' as img_static %}
                <img class="card-img" src="{% static img_static %}" alt="{{beverage.name}}" style="height: 100%"/>
                {% endwith %}
                <div class="card-header">{{beverage.name}}</div>
                <div class="card-body">
                    Price: ${{beverage.price}}
                    <br>
                    {% if beverage.available %}
                    Status: Available
                    {% else %}
                    Status: Out of Stock
                    {% endif %}
                    <br>
                    {% if balance >= beverage.price and beverage.available %}
                    <form action="{% url 'vendingmachine:purchase' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{beverage.id}}">
                        <button type="submit" class="btn btn-primary">Purchase</button>
                    </form>
                    {% else %}
                    <div class="btn btn-secondary">Purchase</div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}